# Generated by Django 5.1.15 on 2026-07-08 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed (will retry)'), ('permanently_failed', 'Permanently failed')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('signature_verified', models.BooleanField(default=False)),
                ('verification_note', models.CharField(blank=True, max_length=255)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('raw_payload', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('normalized', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='processors.paymentprocessor')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='webhooks.webhookevent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['processor', 'event_id'], name='webhooks_we_process_3a89bf_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='webhooks_we_status_81f5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['signature_verified', 'received_at'], name='webhooks_we_signatu_3145bc_idx'),
        ),
    ]
