# Generated by Django 5.1.15 on 2026-07-08 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed (will retry)'), ('permanently_failed', 'Permanently failed')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.CharField(choices=[('hubspot', 'HubSpot (demo)'), ('zoho', 'Zoho (demo)'), ('internal', 'Internal CRM (demo)')], max_length=20)),
                ('source_event_id', models.CharField(blank=True, max_length=120)),
                ('event_type', models.CharField(blank=True, max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deliveries', to='payments.paymentintent')),
            ],
            options={
                'verbose_name': 'CRM delivery',
                'verbose_name_plural': 'CRM deliveries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='crm_crmdeli_status_ada67b_idx'), models.Index(fields=['target', 'status'], name='crm_crmdeli_target_45dc2e_idx')],
            },
        ),
    ]
