# Generated by Django 5.1.15 on 2026-07-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('processors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('statement_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled')], default='pending', max_length=20)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to='processors.paymentprocessor')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-statement_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reported_status', models.CharField(blank=True, max_length=20)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('amount_mismatch', 'Amount mismatch'), ('currency_mismatch', 'Currency mismatch'), ('missing', 'Missing from settlement'), ('unknown', 'Unknown settlement record')], default='unknown', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='settlements.settlementbatch')),
                ('matched_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_items', to='payments.paymentintent')),
            ],
            options={
                'ordering': ('match_status', 'external_reference'),
                'indexes': [models.Index(fields=['match_status'], name='settlements_match_s_9ac24f_idx')],
            },
        ),
    ]
