# Generated by Django 5.1.15 on 2026-07-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('intent_created', 'Payment intent created'), ('intent_duplicate', 'Payment intent duplicate (idempotent)'), ('payment_marked', 'Demo payment marked'), ('webhook_received', 'Webhook received'), ('webhook_verified', 'Webhook signature verified'), ('webhook_rejected', 'Webhook signature rejected'), ('webhook_duplicate', 'Webhook duplicate ignored'), ('webhook_processed', 'Webhook processed'), ('webhook_retried', 'Webhook retried'), ('crm_delivered', 'CRM delivery succeeded'), ('crm_failed', 'CRM delivery failed'), ('crm_retried', 'CRM delivery retried'), ('settlement_imported', 'Settlement batch imported'), ('reconciled', 'Settlement reconciled'), ('login', 'User logged in'), ('logout', 'User logged out')], max_length=40)),
                ('entity_type', models.CharField(blank=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, max_length=120)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
